spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: emailtestmgg@gmail.com
#    password: storeed as env var
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    protocol: smtp
    test-connection: false
  logging:
    level: DEBUG